export const ADD_SPELL = 'ADD_SPELL';
export const DELETE_SPELL = 'DELETE_SPELL';
export const CREATE_SPELLBOOK = "CREATE_SPELLBOOK";
export const DELETE_SPELLBOOK = "DELETE_SPELLBOOK";
export const SELECT_SPELLBOOK = "SELECT_SPELLBOOK";
export const DESELECT_SPELLBOOK = "DESELECT_SPELLBOOK"